{
 "title": "Filament_Laravel_12",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SQL (to My_Filament_Laravel_12  SQL DB on local Docker )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus-average request duration",
     "type": "timeseries",
     "description": "average request duration  ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(app_http_request_duration_seconds_sum[5m]) / rate(app_http_request_duration_seconds_count[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Owners count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "dataset": "dima_laravel_2024_migration", "rawSql": "Select count(*) from owners;" }
     ]
    },
    {
     "title": "Orders",
     "type": "table",
     "description": "ALl list",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "dataset": "dima_laravel_2024_migration",
       "rawSql": "SELECT\r\n  o.id AS order_id,\r\n  o.total_amount AS order_total,\r\n  o.name AS customer_name,\r\n  or_it.id AS order_item_id,\r\n  or_it.product_name AS order_product_name,\r\n  p.sku as product_sku\r\n\r\nFROM orders o\r\nJOIN order_items or_it ON or_it.order_id = o.id\r\nLEFT JOIN products p ON p.id = or_it.id\r\n#LEFT JOIN equipments e ON e.id = ev.equipment_id\r\n#ORDER BY o.id, or_it.id, or_it.product_name;  #You don’t need GROUP BY unless you're doing aggregation\r\n"
      }
     ]
    },
    {
     "title": "Products count",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "dataset": "dima_laravel_2024_migration", "rawSql": "Select count(*) from products;" }
     ]
    },
    {
     "title": "ChatGTP Owners",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "dataset": "dima_laravel_2024_migration",
       "rawSql": "SELECT\r\n    o.first_name AS owner_name,\r\n    COUNT(DISTINCT v.id) AS venue_count,\r\n    COUNT(DISTINCT e.id) AS equip_count,\r\n    GROUP_CONCAT(DISTINCT v.venue_name ORDER BY v.venue_name SEPARATOR ', ') AS venue_names, # all owner venues in one column\r\n\r\n    #GROUP_CONCAT(DISTINCT CONCAT(e.trademark_name, ' ', e.model_name) ORDER BY e.trademark_name SEPARATOR ', ') AS equipment_names, #to list owner 'trademark_name + model name' in one column\r\n\r\n    GROUP_CONCAT(DISTINCT e.trademark_name ORDER BY e.trademark_name SEPARATOR ', ') AS equipment_names,  # to list all owner 'trademark_name' in one column\r\n    GROUP_CONCAT(DISTINCT e.model_name ORDER BY e.model_name SEPARATOR ', ') AS eq_model_names    # to list all owner  'model_name'in one column\r\nFROM owners o\r\nLEFT JOIN venues v ON v.owner_id = o.id\r\nLEFT JOIN equipment_venue ev ON ev.venue_id = v.id\r\nLEFT JOIN equipments e ON e.id = ev.equipment_id\r\nGROUP BY o.id, o.first_name\r\nORDER BY o.first_name;\r\n"
      }
     ]
    },
    {
     "title": "Orders grouped",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "dataset": "laravel_filament",
       "rawSql": "SELECT\n  o.id AS order_id,\n  o.name AS customer_name,\n  o.total_amount AS order_total,\n  GROUP_CONCAT(or_it.product_name ORDER BY or_it.id SEPARATOR ', ') AS order_items\nFROM orders o\nJOIN order_items or_it ON or_it.order_id = o.id\nGROUP BY o.id, o.name, o.total_amount\nORDER BY o.id;\n"
      }
     ]
    },
    {
     "title": "ChatGTP-2 Owners",
     "type": "table",
     "description": "ALl list",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "dataset": "dima_laravel_2024_migration",
       "rawSql": "SELECT\r\n  o.id AS owner_id,\r\n  o.first_name AS owner_name,\r\n  v.id AS venue_id,\r\n  v.venue_name AS venue_name,\r\n  e.id AS equipment_id,\r\n  e.trademark_name,\r\n  e.model_name\r\nFROM owners o\r\nJOIN venues v ON v.owner_id = o.id\r\nLEFT JOIN equipment_venue ev ON ev.venue_id = v.id\r\nLEFT JOIN equipments e ON e.id = ev.equipment_id\r\nORDER BY o.id, v.id, e.trademark_name;\r\n"
      }
     ]
    },
    {
     "title": "Owners with TimeFilter",
     "type": "timeseries",
     "description": ".",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "dataset": "dima_laravel_2024_migration",
       "rawSql": "SELECT\r\n  DATE(created_at) AS time,\r\n  COUNT(*) AS owner_count\r\nFROM\r\n  owners\r\nWHERE\r\n  $__timeFilter(created_at)\r\nGROUP BY\r\n  DATE(created_at)\r\nORDER BY\r\n  time;\r\n"
      }
     ]
    },
    {
     "title": "Owners data (Direct SQL DB)",
     "type": "table",
     "gridPos": { "h": 5, "w": 23, "x": 0, "y": 97 },
     "targets": [
      {
       "dataset": "cashback-dashboard",
       "rawSql": "SELECT \r\n    owner.first_name,\r\n    venue.venue_name,\r\n    equipment.trademark_name,\r\n    COUNT(venue.id) AS venue_count,\r\n    COUNT(equipment.id) AS equipment_count,\r\n    #COUNT(DISTINCT venue.owner_id) as venues_count,\r\n    owner.created_at\r\nFROM \r\n    owners as owner\r\n\r\nINNER JOIN \r\n    venues as venue ON  owner.id = venue.owner_id #AND venue.id = eq_v.venue_id  #pivot table\r\n    \r\nINNER JOIN \r\n   equipment_venue as eq_v ON venue.id = eq_v.venue_id   #pivot table \r\n\r\n\r\nINNER JOIN \r\n    equipments as equipment ON equipment.id = eq_v.equipment_id  #pivot table\r\n\r\n\r\nGROUP BY \r\n    owner.first_name,\r\n    venue.venue_name,\r\n    equipment.trademark_name,\r\n    owner.created_at"
      }
     ]
    },
    {
     "title": "Gets Open API (infinity dataset)",
     "type": "table",
     "description": "gets Api endpoint, sometimes may be not available as service sleeps after some time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
     ]
    }
   ]
  },
  {
   "title": "Infinity (to My_Filament_Laravel_12  Api endpoint on local Docker )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infinity http://localhost:8000/api/owners",
     "type": "table",
     "description": "my api, open route\nUse $.data in Parsing options",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "parser": "backend",
       "root_selector": "$.data\n",
       "source": "url",
       "type": "json",
       "url": "http://my_filament_laravel_12-laravel.test-1:8000/api/owners",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Sanctum protected Api api/bigquery/2topviewed",
     "type": "table",
     "description": "my api, protected route",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "http://my_filament_laravel_12-laravel.test-1:8000/api/bigquery/2topviewed",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus (to Prometheus on local Docker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visits by path count",
     "type": "gauge",
     "description": "total number of visits to various paths using the GET method.\ngroup visits by path and count their values,",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "app_visits_total{method=\"GET\"}\n",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Visits by path time-series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "app_visits_total{method=\"GET\"}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count HTTP statuses",
     "type": "timeseries",
     "description": "To count requests by status, use the +Inf bucket (which includes all requests, regardless of duration), and aggregate by status:",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by (status) (\n  app_http_request_duration_seconds_bucket{method=\"GET\", path=\"dashboard\", le=\"+Inf\"}\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "All HTTP statuses count by duration",
     "type": "timeseries",
     "description": "You’ll get one time series per le bucket, showing the cumulative count of requests that took less than or equal to that duration, regardless of status code.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum by (le) (\n  app_http_request_duration_seconds_bucket{method=\"GET\", path=\"dashboard\"}\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus-average request duration",
     "type": "timeseries",
     "description": "average request duration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(app_http_request_duration_seconds_sum[5m]) / rate(app_http_request_duration_seconds_count[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus-request duration distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum by (le) (rate(app_http_request_duration_seconds_bucket[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "BigQuery (to live Google BigQuery)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "2 most viewed products",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "project": "laravel-bigquery",
       "rawSql": " #top two viewed\n SELECT \n product_id, \n COUNT(product_id) AS total_views \n FROM analytics_dataset.product_views \n GROUP BY product_id \n ORDER BY total_views DESC \n LIMIT 2"
      }
     ]
    }
   ]
  }
 ]
}